# Generated by Django 5.2.6 on 2025-09-21 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0003_alter_channel_avatar_alter_channel_banner'),
        ('content', '0003_alter_video_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendations',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userwatchhistory',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='content.video'),
        ),
        migrations.AlterField(
            model_name='video',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='channel.channel'),
        ),
    ]
