# Generated by Django 5.2.6 on 2025-10-04 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_recommendations_update_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwatchhistory',
            name='liked',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
