# Generated by Django 5.2.6 on 2025-10-29 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_alter_videocomment_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='tags',
            field=models.ManyToManyField(blank=True, db_index=True, to='content.tag'),
        ),
    ]
