# Generated by Django 5.2.6 on 2025-09-21 09:45

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0002_alter_channel_avatar_alter_channel_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='avatar',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='channel/avatar/'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='banner',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='channel/banner/'),
        ),
    ]
